module_name: Elastic Search Module
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
- search
- elastic search
- elastic
- search engine
description_short: This module allows your site to use Elastic Search as the search engine.
description: description.md
images:
- image-1.png
gdpr_compliant: true
license: AFL
php_version:
- 5.6
- 7.0
- 7.1